// ═══════════════════════════════════════════
// Mock Data — akan diganti dengan Supabase
// ═══════════════════════════════════════════

export const aboutData = {
  title: "Full Stack Developer",
  subtitle: "Crafting digital experiences with code & creativity",
  bioShort:
    "Passionate developer yang membangun solusi digital inovatif dengan teknologi modern. Berpengalaman di React, Next.js, Node.js, dan cloud platforms.",
  bioFull:
    "Saya adalah seorang Full Stack Developer dengan passion besar terhadap pengembangan web modern. Dengan pengalaman lebih dari 3 tahun, saya telah membangun berbagai macam proyek mulai dari landing page interaktif hingga aplikasi enterprise yang kompleks.\n\nKeahlian utama saya meliputi ekosistem JavaScript/TypeScript, termasuk React, Next.js, Node.js, dan Express.js. Saya juga familiar dengan teknologi cloud seperti AWS, Vercel, dan Supabase.\n\nSaya percaya bahwa kode yang baik bukan hanya tentang fungsionalitas, tetapi juga tentang pengalaman pengguna yang luar biasa, performa yang optimal, dan desain yang memukau.",
  photoUrl: "/profile.avif",
  resumeUrl: "/resume.pdf",
  location: "Palembang, Indonesia",
  tagline: "Building the future, one line of code at a time.",
};

export const skillsData = [
  { id: "1", name: "React.js", category: "Frontend", proficiency: 92, color: "#61DAFB", isFeatured: true },
  { id: "2", name: "Next.js", category: "Frontend", proficiency: 90, color: "#000000", isFeatured: true },
  { id: "3", name: "TypeScript", category: "Frontend", proficiency: 88, color: "#3178C6", isFeatured: true },
  { id: "4", name: "Tailwind CSS", category: "Frontend", proficiency: 95, color: "#06B6D4", isFeatured: true },
  { id: "5", name: "JavaScript", category: "Frontend", proficiency: 93, color: "#F7DF1E", isFeatured: false },
  { id: "6", name: "HTML/CSS", category: "Frontend", proficiency: 96, color: "#E34F26", isFeatured: false },
  { id: "7", name: "Node.js", category: "Backend", proficiency: 85, color: "#339933", isFeatured: true },
  { id: "8", name: "Express.js", category: "Backend", proficiency: 82, color: "#000000", isFeatured: true },
  { id: "9", name: "Python", category: "Backend", proficiency: 75, color: "#3776AB", isFeatured: false },
  { id: "10", name: "PostgreSQL", category: "Backend", proficiency: 80, color: "#4169E1", isFeatured: false },
  { id: "11", name: "MongoDB", category: "Backend", proficiency: 78, color: "#47A248", isFeatured: false },
  { id: "12", name: "Supabase", category: "Backend", proficiency: 82, color: "#3ECF8E", isFeatured: true },
  { id: "13", name: "React Native", category: "Mobile", proficiency: 72, color: "#61DAFB", isFeatured: false },
  { id: "14", name: "Flutter", category: "Mobile", proficiency: 65, color: "#02569B", isFeatured: false },
  { id: "15", name: "Docker", category: "DevOps", proficiency: 70, color: "#2496ED", isFeatured: false },
  { id: "16", name: "Git & GitHub", category: "Tools", proficiency: 90, color: "#F05032", isFeatured: false },
  { id: "17", name: "Figma", category: "Tools", proficiency: 78, color: "#F24E1E", isFeatured: false },
  { id: "18", name: "AWS", category: "DevOps", proficiency: 68, color: "#FF9900", isFeatured: false },
];

export const projectsData = [
  {
    id: "1",
    title: "E-Commerce Dashboard",
    slug: "e-commerce-dashboard",
    description: "Full-stack e-commerce admin dashboard dengan real-time analytics, manajemen produk, dan sistem order tracking.",
    thumbnail: "/images/projects/ecommerce.jpg",
    liveUrl: "https://demo.example.com",
    githubUrl: "https://github.com/rian/ecommerce",
    techStack: ["Next.js", "TypeScript", "Supabase", "Tailwind CSS", "Chart.js"],
    category: "Web",
    status: "completed",
    isFeatured: true,
    startDate: "2025-06-01",
    endDate: "2025-12-15",
  },
  {
    id: "2",
    title: "Social Media App",
    slug: "social-media-app",
    description: "Aplikasi media sosial dengan fitur real-time chat, post sharing, stories, dan notifikasi push.",
    thumbnail: "/images/projects/social.jpg",
    liveUrl: "https://social.example.com",
    githubUrl: "https://github.com/rian/social",
    techStack: ["React Native", "Node.js", "Socket.io", "MongoDB", "Firebase"],
    category: "Mobile",
    status: "completed",
    isFeatured: true,
    startDate: "2025-01-10",
    endDate: "2025-05-20",
  },
  {
    id: "3",
    title: "AI Content Generator",
    slug: "ai-content-generator",
    description: "Platform AI untuk generate konten marketing, blog posts, dan copywriting dengan integrasi OpenAI GPT.",
    thumbnail: "/images/projects/ai-gen.jpg",
    liveUrl: "https://ai-gen.example.com",
    githubUrl: "https://github.com/rian/ai-gen",
    techStack: ["Next.js", "Python", "FastAPI", "OpenAI", "PostgreSQL"],
    category: "Web",
    status: "completed",
    isFeatured: true,
    startDate: "2025-08-01",
    endDate: "2026-01-30",
  },
  {
    id: "4",
    title: "Task Management API",
    slug: "task-management-api",
    description: "RESTful API untuk manajemen proyek dan task dengan authentication, role-based access, dan real-time updates.",
    thumbnail: "/images/projects/task-api.jpg",
    liveUrl: "",
    githubUrl: "https://github.com/rian/task-api",
    techStack: ["Express.js", "TypeScript", "PostgreSQL", "Redis", "Docker"],
    category: "API",
    status: "completed",
    isFeatured: false,
    startDate: "2024-10-01",
    endDate: "2025-02-28",
  },
  {
    id: "5",
    title: "Fitness Tracker",
    slug: "fitness-tracker",
    description: "Aplikasi tracking kesehatan dan fitness dengan workout planner, nutrition log, dan progress visualization.",
    thumbnail: "/images/projects/fitness.jpg",
    liveUrl: "https://fit.example.com",
    githubUrl: "https://github.com/rian/fitness",
    techStack: ["Flutter", "Dart", "Firebase", "TensorFlow Lite"],
    category: "Mobile",
    status: "completed",
    isFeatured: false,
    startDate: "2024-06-01",
    endDate: "2024-11-30",
  },
  {
    id: "6",
    title: "Portfolio Website",
    slug: "portfolio-website",
    description: "Website portfolio interaktif dengan animasi 3D, dark mode, dan admin CMS untuk mengelola konten.",
    thumbnail: "/images/projects/portfolio.jpg",
    liveUrl: "https://jemiarian.com",
    githubUrl: "https://github.com/rian/portfolio",
    techStack: ["Next.js", "Three.js", "Tailwind CSS", "Supabase", "Express.js"],
    category: "Web",
    status: "in_progress",
    isFeatured: true,
    startDate: "2026-06-01",
    endDate: "",
  },
];

export const experienceData = [
  {
    id: "1",
    type: "work",
    title: "Senior Frontend Developer",
    company: "TechCorp Indonesia",
    location: "Jakarta, Indonesia",
    description:
      "Memimpin tim frontend 5 orang, mengembangkan dashboard analytics perusahaan menggunakan Next.js dan TypeScript. Meningkatkan performa aplikasi 40% dan mengurangi bundle size 30%.",
    startDate: "2025-06-01",
    endDate: "",
    isCurrent: true,
    logoUrl: "",
  },
  {
    id: "2",
    type: "work",
    title: "Full Stack Developer",
    company: "StartupXYZ",
    location: "Remote",
    description:
      "Membangun platform SaaS dari scratch menggunakan React, Node.js, dan PostgreSQL. Mengimplementasikan sistem payment, user management, dan real-time notifications.",
    startDate: "2024-01-15",
    endDate: "2025-05-30",
    isCurrent: false,
    logoUrl: "",
  },
  {
    id: "3",
    type: "internship",
    title: "Web Developer Intern",
    company: "Digital Agency Pro",
    location: "Bandung, Indonesia",
    description:
      "Mengembangkan website klien menggunakan React dan WordPress. Belajar best practices dalam pengembangan web dan version control.",
    startDate: "2023-06-01",
    endDate: "2023-12-31",
    isCurrent: false,
    logoUrl: "",
  },
];

export const achievementsData = [
  {
    id: "1",
    title: "AWS Certified Solutions Architect",
    issuer: "Amazon Web Services",
    description: "Sertifikasi profesional untuk merancang arsitektur cloud yang scalable dan reliable di AWS.",
    dateReceived: "2025-09-15",
    certificateUrl: "https://aws.amazon.com/certification",
    badgeUrl: "https://images.credly.com/images/0e284c3f-5164-4b21-8660-0d84737941bc/image.png",
  },
  {
    id: "2",
    title: "Hackathon Winner — InnovateTech 2025",
    issuer: "InnovateTech",
    description: "Juara 1 hackathon nasional dengan proyek AI-powered accessibility tool untuk tunanetra.",
    dateReceived: "2025-03-20",
    certificateUrl: "",
    badgeUrl: "",
  },
  {
    id: "3",
    title: "Google Professional Cloud Developer",
    issuer: "Google Cloud",
    description: "Sertifikasi untuk merancang, membangun, dan mengelola solusi di Google Cloud Platform.",
    dateReceived: "2024-11-10",
    certificateUrl: "https://cloud.google.com/certification",
    badgeUrl: "https://images.credly.com/images/08096465-cbfc-4c3e-93e5-93c5aa61f23e/image.png",
  },
  {
    id: "4",
    title: "Meta Frontend Developer Certificate",
    issuer: "Meta (Coursera)",
    description: "Professional certificate dalam pengembangan frontend dengan React dari Meta.",
    dateReceived: "2024-05-01",
    certificateUrl: "",
    badgeUrl: "",
  },
];

export const educationData = [
  {
    id: "1",
    institution: "Universitas Indonesia",
    degree: "S1",
    fieldOfStudy: "Teknik Informatika",
    startDate: "2020-08-01",
    endDate: "2024-07-31",
    isCurrent: false,
    description: "Lulus dengan predikat Cum Laude. Aktif di komunitas developer kampus dan menjadi asisten lab pemrograman.",
    grade: "3.85/4.00",
  },
];

export const hobbiesData = [
  { id: "1", name: "Coding", description: "Membangun side projects dan berkontribusi ke open source", icon: "Code2" },
  { id: "2", name: "Gaming", description: "Competitive & casual gaming, game development", icon: "Gamepad2" },
  { id: "3", name: "Photography", description: "Street photography dan landscape", icon: "Camera" },
  { id: "4", name: "Music", description: "Bermain gitar dan produksi musik digital", icon: "Music" },
  { id: "5", name: "Reading", description: "Tech blogs, sci-fi novels, dan self-improvement", icon: "BookOpen" },
  { id: "6", name: "Traveling", description: "Explore tempat baru dan budaya berbeda", icon: "Plane" },
];

export const socialLinksData = [
  { id: "1", platform: "GitHub", url: "https://github.com/rian", icon: "Github" },
  { id: "2", platform: "LinkedIn", url: "https://linkedin.com/in/rian", icon: "Linkedin" },
  { id: "3", platform: "Twitter", url: "https://twitter.com/rian", icon: "Twitter" },
  { id: "4", platform: "Instagram", url: "https://instagram.com/rian", icon: "Instagram" },
  { id: "5", platform: "YouTube", url: "https://youtube.com/@rian", icon: "Youtube" },
];

export const contactMessagesData = [
  {
    id: "1",
    name: "John Smith",
    email: "john@company.com",
    subject: "Job Opportunity",
    message: "Hi Jemi Arian, I saw your portfolio and we have an exciting opportunity at our company...",
    isRead: false,
    isStarred: true,
    createdAt: "2026-06-18T10:30:00Z",
  },
  {
    id: "2",
    name: "Sarah Johnson",
    email: "sarah@startup.io",
    subject: "Freelance Project",
    message: "Hello! We're looking for a developer to build a web app. Would you be interested?",
    isRead: true,
    isStarred: false,
    createdAt: "2026-06-15T14:20:00Z",
  },
  {
    id: "3",
    name: "Mike Chen",
    email: "mike@dev.co",
    subject: "Collaboration",
    message: "Hey Jemi Arian, love your work! Would you like to collaborate on an open-source project?",
    isRead: false,
    isStarred: false,
    createdAt: "2026-06-12T09:15:00Z",
  },
];
